---
- name: play to demonstrate archive
  hosts: [192.168.1.39, 192.168.1.44]
  become: true
  tasks: 
   - name: Task to archive remote server /etc 
     archive: 
      path: /etc
      dest: /tmp/etc_archive.tar.gz
      format: gz
      owner: ansible
      group: ansible
      mode: '0600'
... 