--- 
- name: Demonstrate ansible register variable
  hosts: localhost
  become: true
  remote_user: ansible
  tasks:
   - name: Task to register a variable
     service:
      name: crond
      state: restarted
     register: myvar
   - name: Print myvar content
     debug:
      msg: The daemon is {{myvar.name}} and it is {{myvar.state}}
      #msg: the content is {{myvar}}
      #msg: the daemon is{{myvar['name']}} and it is {{myvar['state']}}
...