--- 
- name: disable direct root login using ssh
  hosts: all
  become: true
  remote_user: ansible
  tasks:
   - name: task to modify(replace) permit root logins on /etc/ssh/sshd_config file
     replace:
      path: /etc/ssh/sshd_config
      regexp: '^PermitRootLogin yes'
      replace: 'PermitRootLogin no'
      backup: yes
   - name: restart sshd daemon after changing conf file 
     service:
       name: sshd
       state: restarted
...