- name: create a user with given variables
  hosts: localhost
  become: yes
  remote_user: ansible
  become_user: root
  vars_files:
  - vars/pass.txt
  tasks:
  - name: create user
    user:
      name: likhithadamm
      password: "{{ password|password_hash('sha512') }}"
      update_password: on_create
      state: present
...